### ISSUE TITLE
HRHiringAppLab.exe never works

### ISSUE THREAD

**Issue by JuanKRuiz** [OfficeDev/msteams-sample-contoso-hr-talent-app#4]
We ( I mean me and a couple of other colleages) are trying to run the lab setup, but the execution raise an exception and the script never  runs.

---------------------------
Failed verification
---------------------------
This script may have been copied from it's original location and is not valid for use on this computer.
---------------------------
OK   
---------------------------
![image](https://user-images.githubusercontent.com/1454560/69892996-9d086e00-12d9-11ea-8b9b-581651488ac2.png)

**Comment by oljago** [comment]
We have removed the script and updated the instructions.
